### ISSUE TITLE
tsx写法转换时报错了

### ISSUE THREAD

**Issue by XshGentleman** [tenadolanter/i18n-cli#11]
return (
          <div class="p-1" onClick={changeModal.bind(null, true)}>
            <Tooltip>
              {{
                title: () => t('common.searchText'),
                default: () => <SearchOutlined />,
              }}
            </Tooltip>
            <AppSearchModal onClose={changeModal.bind(null, false)} visible={unref(showModal)} />
          </div>
        );

**Comment by tenadolanter** [comment]
原始代码是什么，贴出来看看 @XshGentleman
