### ISSUE TITLE
建议保留原来文本作为默认值，增加代码可读性以及二次修改

### ISSUE THREAD

**Issue by bobolau** [tenadolanter/i18n-cli#9]
建议保留原来文本作为默认值，增加代码可读性以及二次修改
例如
转换前： 测试
转换后：i18n.t('ce-shi','测试')

**Comment by tenadolanter** [comment]
@bobolau  收到，我记个TODO，后面扩展出一个配置项，用来控制这个是否使用这个功能

**Comment by tenadolanter** [comment]
添加了keyShowOrigin属性，控制是否限制中文 @bobolau
